//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCN_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyLop
    {
        public int LopHocID { get; set; }
        public int SinhVienID { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public string TrangThai { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
