//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCN_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanh
    {
        public int DiemDanhID { get; set; }
        public int BuoiHocID { get; set; }
        public int SinhVienID { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> ThoiGianCheckin { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NguoiDiemDanh { get; set; }
    
        public virtual BuoiHoc BuoiHoc { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
