//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCN_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.DiemDanhs = new HashSet<DiemDanh>();
            this.LopHocs = new HashSet<LopHoc>();
        }
    
        public string MaKhoa { get; set; }
        public int GiangVienID { get; set; }
        public string MaGV { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Diachi { get; set; }
        public string GioiTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanh> DiemDanhs { get; set; }
        public virtual KHOA KHOA { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHoc> LopHocs { get; set; }
    }
}
