//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCN_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.BuoiHocs = new HashSet<BuoiHoc>();
            this.DangKyLops = new HashSet<DangKyLop>();
        }
    
        public string Tenlop { get; set; }
        public int LopHocID { get; set; }
        public int MonHocID { get; set; }
        public int GiangVienID { get; set; }
        public string HocKy { get; set; }
        public string NamHoc { get; set; }
        public string PhongHoc { get; set; }
        public Nullable<int> SiSoToiDa { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuoiHoc> BuoiHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKyLop> DangKyLops { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
